/**
 * American -> British spelling map. Not exhaustive - a maintained list
 * covering the vocabulary this brand actually writes in (formulation
 * science, skincare, business/founder narration). Extend as new false
 * negatives turn up in drafts.
 */
export const AMERICAN_TO_BRITISH: Record<string, string> = {
  color: "colour",
  colors: "colours",
  colored: "coloured",
  coloring: "colouring",
  moisturizer: "moisturiser",
  moisturizers: "moisturisers",
  moisturize: "moisturise",
  moisturized: "moisturised",
  moisturizing: "moisturising",
  oxidize: "oxidise",
  oxidizes: "oxidises",
  oxidized: "oxidised",
  oxidizing: "oxidising",
  oxidization: "oxidisation",
  sensitization: "sensitisation",
  sensitize: "sensitise",
  sensitized: "sensitised",
  sensitizing: "sensitising",
  standardized: "standardised",
  standardize: "standardise",
  standardizing: "standardising",
  program: "programme",
  programs: "programmes",
  analyze: "analyse",
  analyzed: "analysed",
  analyzing: "analysing",
  analyzes: "analyses",
  center: "centre",
  centers: "centres",
  centered: "centred",
  favorite: "favourite",
  favorites: "favourites",
  behavior: "behaviour",
  behaviors: "behaviours",
  behavioral: "behavioural",
  flavor: "flavour",
  flavors: "flavours",
  humor: "humour",
  labor: "labour",
  neighbor: "neighbour",
  neighbors: "neighbours",
  fiber: "fibre",
  fibers: "fibres",
  liter: "litre",
  liters: "litres",
  theater: "theatre",
  theaters: "theatres",
  defense: "defence",
  offense: "offence",
  pretense: "pretence",
  organize: "organise",
  organized: "organised",
  organizing: "organising",
  organization: "organisation",
  organizations: "organisations",
  recognize: "recognise",
  recognized: "recognised",
  recognizes: "recognises",
  recognizing: "recognising",
  utilize: "utilise",
  utilized: "utilised",
  utilizes: "utilises",
  utilizing: "utilising",
  characterize: "characterise",
  characterized: "characterised",
  characterizes: "characterises",
  minimize: "minimise",
  minimized: "minimised",
  minimizes: "minimises",
  maximize: "maximise",
  maximized: "maximised",
  maximizes: "maximises",
  summarize: "summarise",
  summarized: "summarised",
  emphasize: "emphasise",
  emphasized: "emphasised",
  emphasizes: "emphasises",
  optimize: "optimise",
  optimized: "optimised",
  optimizes: "optimises",
  optimizing: "optimising",
  stabilize: "stabilise",
  stabilized: "stabilised",
  stabilizes: "stabilises",
  stabilizing: "stabilising",
  stabilizer: "stabiliser",
  stabilizers: "stabilisers",
  personalize: "personalise",
  personalized: "personalised",
  generalize: "generalise",
  generalized: "generalised",
  specialize: "specialise",
  specialized: "specialised",
  realize: "realise",
  realized: "realised",
  realizes: "realises",
  apologize: "apologise",
  capitalize: "capitalise",
  criticize: "criticise",
  criticized: "criticised",
  hospitalize: "hospitalise",
  initialize: "initialise",
  localize: "localise",
  memorize: "memorise",
  modernize: "modernise",
  mobilize: "mobilise",
  neutralize: "neutralise",
  neutralized: "neutralised",
  normalize: "normalise",
  normalized: "normalised",
  pasteurize: "pasteurise",
  pasteurized: "pasteurised",
  polarize: "polarise",
  prioritize: "prioritise",
  prioritized: "prioritised",
  rationalize: "rationalise",
  symbolize: "symbolise",
  synthesize: "synthesise",
  synthesized: "synthesised",
  visualize: "visualise",
  gray: "grey",
  grayish: "greyish",
  mold: "mould",
  molds: "moulds",
  molded: "moulded",
  odor: "odour",
  odors: "odours",
  rigor: "rigour",
  tumor: "tumour",
  vapor: "vapour",
  catalog: "catalogue",
  catalogs: "catalogues",
  dialog: "dialogue",
  dialogs: "dialogues",
  skeptical: "sceptical",
  skepticism: "scepticism",
  traveled: "travelled",
  traveling: "travelling",
  canceled: "cancelled",
  canceling: "cancelling",
  modeled: "modelled",
  modeling: "modelling",
};

export interface SpellingViolation {
  american: string;
  british: string;
  index: number;
}

export function findSpellingViolations(text: string): SpellingViolation[] {
  const violations: SpellingViolation[] = [];
  const pattern = /[A-Za-z]+/g;
  for (const match of text.matchAll(pattern)) {
    if (match.index === undefined) continue;
    const word = match[0];
    const british = AMERICAN_TO_BRITISH[word.toLowerCase()];
    if (british) {
      violations.push({ american: word, british, index: match.index });
    }
  }
  return violations;
}
